#!/usr/bin/env python3
"""Generate full Unicode general-category range data from CPython.

Emits `chardet/src/codecs/categories_data.rs` with a run-length encoded
`(start, end, category_index)` table covering all of Unicode, so the Rust
port reproduces `unicodedata.category` exactly for any codepoint.
"""
from __future__ import annotations

import sys
import unicodedata

INT_TO_CATEGORY = {
    0: "Lu", 1: "Ll", 2: "Lt", 3: "Lm", 4: "Lo", 5: "Mn", 6: "Mc", 7: "Me",
    8: "Nd", 9: "Nl", 10: "No", 11: "Pc", 12: "Pd", 13: "Ps", 14: "Pe",
    15: "Pi", 16: "Pf", 17: "Po", 18: "Sm", 19: "Sc", 20: "Sk", 21: "So",
    22: "Zs", 23: "Zl", 24: "Zp", 25: "Cc", 26: "Cf", 27: "Cs", 28: "Co",
    29: "Cn",
}
CATEGORY_TO_INT = {v: k for k, v in INT_TO_CATEGORY.items()}


def main() -> None:
    ranges = []
    prev = None
    start = 0
    for cp in range(0x110000):
        cat = CATEGORY_TO_INT[unicodedata.category(chr(cp))]
        if cat != prev:
            if prev is not None:
                ranges.append((start, cp - 1, prev))
            start = cp
            prev = cat
    ranges.append((start, 0x110000 - 1, prev))

    o = []
    o.append("// @generated by scripts_generate/gen_categories.py -- do not edit.")
    o.append("")
    o.append("/// Category name by index (matches chardet's `_INT_TO_CATEGORY`).")
    o.append("#[rustfmt::skip]")
    o.append("pub static CATEGORY_NAMES: [&str; 30] = [")
    for i in range(30):
        o.append(f'    "{INT_TO_CATEGORY[i]}",')
    o.append("];")
    o.append("")
    o.append("/// Run-length encoded `(start, end_inclusive, category_index)`.")
    o.append("#[rustfmt::skip]")
    o.append("pub static CATEGORY_RANGES: &[(u32, u32, u8)] = &[")
    line = "   "
    for s, e, c in ranges:
        item = f" ({s},{e},{c}),"
        if len(line) + len(item) > 98:
            o.append(line)
            line = "   "
        line += item
    if line.strip():
        o.append(line)
    o.append("];")
    print("\n".join(o))


if __name__ == "__main__":
    main()
