#!/usr/bin/env python3
"""Generate `chardet/src/registry.rs` from the Python registry (exact parity)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, "/tmp/opencode/chardet/src")
from chardet.registry import REGISTRY, _REGISTRY_ENTRIES  # noqa: E402
from chardet.enums import EncodingEra  # noqa: E402


def era_expr(era: EncodingEra) -> str:
    parts = []
    for name in ("MODERN_WEB", "LEGACY_ISO", "LEGACY_MAC", "LEGACY_REGIONAL", "DOS", "MAINFRAME"):
        if era & getattr(EncodingEra, name):
            parts.append(f"Era::{name}")
    return " | ".join(parts) if parts else "0"


def rs_str_array(items) -> str:
    if not items:
        return "&[]"
    inner = ", ".join(f'"{x}"' for x in items)
    return f"&[{inner}]"


def main() -> None:
    o = []
    o.append("// @generated by scripts_generate/gen_registry.py -- do not edit.")
    o.append("// Transcribed from chardet 7's chardet/registry.py.")
    o.append("")
    o.append("use crate::enums::Era;")
    o.append("")
    o.append("/// Metadata for a single encoding.")
    o.append("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    o.append("pub struct EncodingInfo {")
    o.append("    pub name: &'static str,")
    o.append("    pub aliases: &'static [&'static str],")
    o.append("    pub era: u8,")
    o.append("    pub is_multibyte: bool,")
    o.append("    pub languages: &'static [&'static str],")
    o.append("}")
    o.append("")
    o.append("#[rustfmt::skip]")
    o.append("pub static REGISTRY_ENTRIES: &[EncodingInfo] = &[")
    for e in _REGISTRY_ENTRIES:
        o.append("    EncodingInfo {")
        o.append(f'        name: "{e.name}",')
        o.append(f"        aliases: {rs_str_array(e.aliases)},")
        o.append(f"        era: {era_expr(e.era)},")
        o.append(f"        is_multibyte: {'true' if e.is_multibyte else 'false'},")
        o.append(f"        languages: {rs_str_array(e.languages)},")
        o.append("    },")
    o.append("];")
    o.append("")
    # Complete CPython alias set: every alias in Python's codec alias table that
    # resolves to one of our registry encodings.  This closes lookups such as
    # "IBM775" -> cp775 that the curated alias lists do not spell out.
    import codecs
    from encodings import aliases as _aliases

    def norm(s: str) -> str:
        return "".join(c.lower() if c.isalnum() else "_" for c in s)

    canon: dict[str, str] = {}
    for e in _REGISTRY_ENTRIES:
        canon[norm(e.name)] = e.name
        for a in e.aliases:
            canon.setdefault(norm(a), e.name)
    extra: dict[str, str] = {}
    for alias in _aliases.aliases:
        try:
            pycanon = codecs.lookup(alias).name
        except (LookupError, ValueError):
            continue
        c = canon.get(norm(pycanon)) or canon.get(norm(alias))
        if c is None:
            continue
        key = norm(alias)
        if key not in canon and key not in extra:
            extra[key] = c
    o.append("/// Normalized CPython alias -> canonical registry name.")
    o.append("#[rustfmt::skip]")
    o.append("pub static PY_ALIASES: &[(&str, &str)] = &[")
    for k in sorted(extra):
        o.append(f'    ("{k}", "{extra[k]}"),')
    o.append("];")
    print("\n".join(o))


if __name__ == "__main__":
    main()
