#!/usr/bin/env python3
"""Generate Rust codec data tables from CPython's codecs (exact parity).

Produces `chardet/src/codecs/sbcs_data.rs` containing, for every registry
encoding:

* a 256-entry decode table (Unicode scalar value or 0xFFFF_FFFF when the
  single byte is undefined/undecodable);
* a 256-entry letter-case table (0 = not a letter, 1 = uppercase letter,
  2 = other letter / combining mark), matching chardet's
  ``_letter_case_table``.

Run from the chardet source checkout:
    python3 scripts_generate/gen_codec_tables.py > out.rs
"""
from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

# Make the chardet source importable.
SRC = Path("/tmp/opencode/chardet/src")
sys.path.insert(0, str(SRC))

from chardet.registry import REGISTRY  # noqa: E402

INVALID = 0xFFFF_FFFF


def decode_byte(enc: str, b: int) -> int:
    try:
        ch = bytes([b]).decode(enc)
    except UnicodeDecodeError:
        return INVALID
    except Exception:
        return INVALID
    if len(ch) != 1:
        return INVALID
    return ord(ch)


def case_of(enc: str, b: int) -> int:
    cp = decode_byte(enc, b)
    if cp == INVALID:
        return 0
    ch = chr(cp)
    cat = unicodedata.category(ch)
    if cat == "Lu":
        return 1
    if cat[0] == "L" or cat in ("Mn", "Mc"):
        return 2
    return 0


def main() -> None:
    names = sorted(REGISTRY.keys())
    out = []
    out.append("// @generated by scripts_generate/gen_codec_tables.py -- do not edit.")
    out.append("// Derived from CPython's codecs/unicodedata for exact parity.")
    out.append("")
    out.append("pub const INVALID: u32 = 0xFFFF_FFFF;")
    out.append("")
    # case tables for every encoding
    out.append("/// 256-entry letter-case table per encoding: 0=non-letter, 1=Lu, 2=other L/M.")
    out.append("pub fn letter_case(name: &str) -> Option<&'static [u8; 256]> {")
    out.append("    match name {")
    for name in names:
        table = [case_of(name, b) for b in range(256)]
        # skip all-zero tables to save space? keep for simplicity but emit compactly
        arr = ",".join(str(v) for v in table)
        out.append(f'        "{name}" => Some(&[{arr}]),')
    out.append("        _ => None,")
    out.append("    }")
    out.append("}")
    out.append("")
    # single-byte decode tables for SBCS encodings
    out.append("/// 256-entry Unicode decode table per single-byte encoding.")
    out.append("pub fn sbcs_decode(name: &str) -> Option<&'static [u32; 256]> {")
    out.append("    match name {")
    for name in names:
        entry = REGISTRY[name]
        if entry.is_multibyte:
            continue
        if name in ("utf-8", "utf-8-sig", "utf-16", "utf-16-be", "utf-16-le",
                    "utf-32", "utf-32-be", "utf-32-le", "utf-7", "ascii"):
            continue
        table = [decode_byte(name, b) for b in range(256)]
        arr = ",".join(("INVALID" if v == INVALID else str(v)) for v in table)
        out.append(f'        "{name}" => Some(&[{arr}]),')
    out.append("        _ => None,")
    out.append("    }")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
